
/**
 * Author Type
 *
 * Distinguishes between human and AI-generated content.
 */
export enum AuthorType {
  AI = 'ai',                    // Content generated by a language model or AI service.
  HUMAN = 'human',              // Content created by a human user.
}

/**
 * The Author Model
 *
 * Represents the public-facing identity of a content creator (name, avatar,
 * branding, trust signals). This is the persona readers see and trust.
 */
export interface Author {
  id: string;

  // Identity
  name: string;                         // e.g., "Grok 4", "AI News Assistant, "Jane Doe", etc.
  slug: string;                         // e.g., "grok-4", "ai-news-assistant", "jane-doe", etc.
  role?: string | null;                 // e.g., "Lead Data Analyst" or "AI Content Generator"

  // Branding & Trust       
  avatarUrl?: string | null;            // e.g., "https://openai.com/favicon.svg", etc.  
  bio?: string | null;                  // e.g., "AI assistant by xAI", etc.
  website?: string | null;              // e.g., "https://openai.com", etc.
  // isVerified?: boolean;  

  // Metadata
  type?: AuthorType | string | null;    // "AI", "Human", "Robot", etc.
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
  // deactivatedAt?: string;
}


/**
 * Author Creation Input (DTO)
 * 
 * Minimal data required to create a new author.
 */
export interface CreateAuthorDTO extends Partial<Omit<Author, 'id' | 'createdAt' | 'updatedAt'>> {
  name: string;
  email: string;
  bio?: string;
  slug?: string;
}

/**
 * Author Update Input (DTO)
 * 
 * Partial update allowing most fields to change. Excludes system-managed
 * and immutable fields (id, createdAt, updatedAt).
 */
export interface UpdateAuthorDTO extends Partial<Omit<Author, 'id' | 'createdAt' | 'updatedAt'>> {
  name?: string;
  email?: string;
  bio?: string;
  slug?: string;
}