import { useEffect, useState } from 'react';
import { ArticleCard } from '@/components/article/ArticleCard';
import { ArticleCardSkeleton } from '@/components/article/ArticleCardSkeleton';
import { Button } from '@/components/ui/button';
import { api } from '@/services/api';
import type { Article, PaginatedApiResponse } from '@/types';
import { AlertCircle } from 'lucide-react';

/**
 * Home Page
 */
export function HomePage() {
  const [articles, setArticles] = useState<Article[]>([]);
  const [pagination, setPagination] = useState({
    page: 1,
    totalPages: 1,
    hasNext: false,
    hasPrev: false,
  });
  const [loading, setLoading] = useState(true);
  const [showSkeleton, setShowSkeleton] = useState(false);
  const [error, setError] = useState<string | null>(null);
  
  const loadArticles = async (page: number) => {
    try {
      setLoading(true);
      setError(null);
      
      // Only show skeleton after 400ms delay (prevents flash)
      const skeletonTimer = setTimeout(() => {
        setShowSkeleton(true);
      }, 400);
      
      const response: PaginatedApiResponse<Article> = await api.getArticlesFeed(page, 12);
      
      clearTimeout(skeletonTimer);
      setArticles(response.data || []);
      setPagination({
        page: response.pagination.page,
        totalPages: response.pagination.totalPages,
        hasNext: response.pagination.hasNext,
        hasPrev: response.pagination.hasPrev,
      });
    } catch (err: any) {
      setError(err.message || 'Failed to load articles');
    } finally {
      setLoading(false);
      setShowSkeleton(false);
    }
  };
  
  useEffect(() => {
    loadArticles(1);
  }, []);
  
  const handlePageChange = (newPage: number) => {
    loadArticles(newPage);
    window.scrollTo({ top: 0, behavior: 'smooth' });
  };
  
  return (
    <div className="container mx-auto px-4 py-12">
      {/* Hero Section */}
      <div className="text-center mb-12">
        <h1 className="text-4xl md:text-5xl font-bold tracking-tight mb-4">
          Welcome to AI Blog
        </h1>
        <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
          Discover articles automatically generated by artificial intelligence,
          covering technology, programming, and innovation.
        </p>
      </div>
      
      {/* Error State */}
      {error && (
        <div className="flex items-center justify-center gap-2 p-4 mb-8 rounded-lg" style={{
          backgroundColor: 'hsl(var(--color-destructive) / 0.1)',
          color: 'hsl(var(--color-destructive))'
        }}>
          <AlertCircle className="h-5 w-5" />
          <p>{error}</p>
        </div>
      )}
      
      {/* Loading State (only after delay) */}
      {loading && showSkeleton && (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {Array.from({ length: 6 }).map((_, i) => (
            <ArticleCardSkeleton key={i} />
          ))}
        </div>
      )}
      
      {/* Articles Grid */}
      {!showSkeleton && articles.length > 0 && (
        <>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 mb-12">
            {articles.map((article) => (
              <ArticleCard key={article.id} article={article} />
            ))}
          </div>
          
          {/* Pagination */}
          {pagination.totalPages > 1 && (
            <div className="flex items-center justify-center gap-4">
              <Button
                variant="outline"
                onClick={() => handlePageChange(pagination.page - 1)}
                disabled={!pagination.hasPrev}
              >
                Previous
              </Button>
              
              <span className="text-sm text-muted-foreground">
                Page {pagination.page} of {pagination.totalPages}
              </span>
              
              <Button
                variant="outline"
                onClick={() => handlePageChange(pagination.page + 1)}
                disabled={!pagination.hasNext}
              >
                Next
              </Button>
            </div>
          )}
        </>
      )}
      
      {/* Empty State */}
      {!loading && !showSkeleton && articles.length === 0 && !error && (
        <div className="text-center py-12">
          <p className="text-lg text-muted-foreground">
            No articles found. Check back soon!
          </p>
        </div>
      )}
    </div>
  );
}