import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { memo } from 'react';
import { Calendar, Clock, User, Eye } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { formatDate } from '@/lib/utils';
import type { Article } from '@/types';

interface ArticleContentProps {
  article: Article;
}

/**
 * Article Content Component
 */
function ArticleContentComponent({ article }: ArticleContentProps) {
  return (
    <article className="mx-auto max-w-4xl">
      {/* Featured Image */}
      {article.featuredImage && (
        <div className="relative mb-8 overflow-hidden rounded-lg">
          <img
            src={article.featuredImage}
            alt={article.imageAlt || article.title}
            className="w-full h-auto object-cover"
          />
        </div>
      )}
      
      {/* Category Badge */}
      {article.category && (
        <div className="mb-4">
          <Badge variant="secondary">{article.category.name}</Badge>
        </div>
      )}
      
      {/* Title */}
      <h1 className="text-4xl md:text-5xl font-bold tracking-tight mb-4">
        {article.title}
      </h1>
      
      {/* Excerpt */}
      {article.excerpt && (
        <p className="text-xl text-muted-foreground mb-6">
          {article.excerpt}
        </p>
      )}
      
      {/* Metadata */}
      <div className="flex flex-wrap items-center gap-4 mb-8 pb-8 border-b text-sm text-muted-foreground">
        {/* Author */}
        {article.author && (
          <div className="flex items-center gap-2">
            {article.author.avatarUrl && (
              <img
                src={article.author.avatarUrl}
                alt={article.author.name}
                className="h-10 w-10 rounded-full"
              />
            )}
            <div>
              <div className="flex items-center gap-1 font-medium text-foreground">
                <User className="h-4 w-4" />
                <span>{article.author.name}</span>
              </div>
              {article.author.role && (
                <div className="text-xs">{article.author.role}</div>
              )}
            </div>
          </div>
        )}
        
        <div className="flex flex-wrap items-center gap-4 ml-auto">
          {/* Published Date */}
          {article.publishedAt && (
            <div className="flex items-center gap-1">
              <Calendar className="h-4 w-4" />
              <span>{formatDate(article.publishedAt)}</span>
            </div>
          )}
          
          {/* Reading Time */}
          {article.readingTimeMinutes && (
            <div className="flex items-center gap-1">
              <Clock className="h-4 w-4" />
              <span>{article.readingTimeMinutes} min read</span>
            </div>
          )}
          
          {/* View Count */}
          {article.stats && (
            <div className="flex items-center gap-1">
              <Eye className="h-4 w-4" />
              <span>{Number(article.stats.views).toLocaleString()} views</span>
            </div>
          )}
        </div>
      </div>
      
      {/* Article Body (Markdown) */}
      <div className="prose prose-slate !max-w-none">
        <ReactMarkdown remarkPlugins={[remarkGfm]}>
          {article.body}
        </ReactMarkdown>
      </div>
      
      {/* Tags */}
      {article.tags && article.tags.length > 0 && (
        <div className="mt-12 pt-8 border-t">
          <h3 className="text-sm font-semibold mb-4">Tags</h3>
          <div className="flex flex-wrap gap-2">
            {article.tags.map((tag) => (
              <Badge key={tag.id} variant="outline">
                {tag.name}
              </Badge>
            ))}
          </div>
        </div>
      )}
      
      {/* AI Attribution */}
      {article.generatedBy && (
        <div className="mt-8 p-4 rounded-lg text-sm" style={{ 
          backgroundColor: 'hsl(var(--color-muted) / 0.5)',
          color: 'hsl(var(--color-muted-foreground))'
        }}>
          <p>
            This article was generated by AI using{' '}
            <span className="font-medium">{article.generatedBy.model}</span>
            {article.generatedBy.topic && (
              <> on the topic of <span className="font-medium">{article.generatedBy.topic}</span></>
            )}
            .
          </p>
        </div>
      )}
    </article>
  );
}

export const ArticleContent = memo(ArticleContentComponent);